// NOTE: This file is generated by tool/update_pbem.rb
package parser

import (
	"reflect"

	dota "github.com/elobuff/d2rp/dota"
)

const (
	BaseError ParserBaseEvent = iota
	DEM_ClassInfo
	DEM_ConsoleCmd
	DEM_CustomData
	DEM_CustomDataCallbacks
	DEM_FileHeader
	DEM_FileInfo
	DEM_FullPacket
	DEM_IsCompressed
	DEM_Max
	DEM_Packet
	DEM_SendTables
	DEM_SignonPacket
	DEM_Stop
	DEM_StringTables
	DEM_SyncTick
	DEM_UserCmd
	DOTA_UM_AIDebugLine
	DOTA_UM_AddQuestLogEntry
	DOTA_UM_AddUnitToSelection
	DOTA_UM_BotChat
	DOTA_UM_CharacterSpeakConcept
	DOTA_UM_ChatEvent
	DOTA_UM_ChatWheel
	DOTA_UM_CombatHeroPositions
	DOTA_UM_CombatLogData
	DOTA_UM_CombatLogShowDeath
	DOTA_UM_CreateLinearProjectile
	DOTA_UM_DestroyLinearProjectile
	DOTA_UM_DodgeTrackingProjectiles
	DOTA_UM_GamerulesStateChanged
	DOTA_UM_GlobalLightColor
	DOTA_UM_GlobalLightDirection
	DOTA_UM_HalloweenDrops
	DOTA_UM_HudError
	DOTA_UM_InvalidCommand
	DOTA_UM_ItemAlert
	DOTA_UM_ItemFound
	DOTA_UM_ItemPurchased
	DOTA_UM_LocationPing
	DOTA_UM_MapLine
	DOTA_UM_MiniKillCamInfo
	DOTA_UM_MinimapDebugPoint
	DOTA_UM_MinimapEvent
	DOTA_UM_NevermoreRequiem
	DOTA_UM_OverheadEvent
	DOTA_UM_ParticleManager
	DOTA_UM_Ping
	DOTA_UM_ReceivedXmasGift
	DOTA_UM_SendGenericToolTip
	DOTA_UM_SendRoshanPopup
	DOTA_UM_SendStatPopup
	DOTA_UM_SetNextAutobuyItem
	DOTA_UM_SharedCooldown
	DOTA_UM_ShowSurvey
	DOTA_UM_SpectatorPlayerClick
	DOTA_UM_SwapVerify
	DOTA_UM_TournamentDrop
	DOTA_UM_TutorialFade
	DOTA_UM_TutorialFinish
	DOTA_UM_TutorialPingMinimap
	DOTA_UM_TutorialRequestExp
	DOTA_UM_TutorialTipInfo
	DOTA_UM_UnitEvent
	DOTA_UM_UpdateSharedContent
	DOTA_UM_WorldLine
	UM_AchievementEvent
	UM_CloseCaption
	UM_CloseCaptionDirect
	UM_CurrentTimescale
	UM_DesiredTimescale
	UM_Fade
	UM_GameTitle
	UM_Geiger
	UM_HintText
	UM_HudMsg
	UM_HudText
	UM_KeyHintText
	UM_MAX_BASE
	UM_MessageText
	UM_RequestState
	UM_ResetHUD
	UM_Rumble
	UM_SayText
	UM_SayText2
	UM_SayTextChannel
	UM_SendAudio
	UM_Shake
	UM_ShakeDir
	UM_StatsCrawlMsg
	UM_StatsSkipState
	UM_TextMsg
	UM_Tilt
	UM_Train
	UM_VGUIMenu
	UM_VoiceMask
	UM_VoiceSubtitle
	net_Disconnect
	net_File
	net_NOP
	net_SetConVar
	net_SignonState
	net_SplitScreenUser
	net_StringCmd
	net_Tick
	svc_BSPDecal
	svc_ClassInfo
	svc_CreateStringTable
	svc_CrosshairAngle
	svc_EntityMessage
	svc_FixAngle
	svc_GameEvent
	svc_GameEventList
	svc_GetCvarValue
	svc_Menu
	svc_PacketEntities
	svc_PacketReliable
	svc_Prefetch
	svc_Print
	svc_SendTable
	svc_ServerInfo
	svc_SetPause
	svc_SetView
	svc_Sounds
	svc_SplitScreen
	svc_TempEntities
	svc_UpdateStringTable
	svc_UserMessage
	svc_VoiceData
	svc_VoiceInit
)

var NetSvc []ParserBaseEventMap
var BumDum []ParserBaseEventMap
var Maps = map[string]ParserBaseEventMap{}

func init() {
	NetSvc = []ParserBaseEventMap{
		{MapType: NET, Value: 0, Name: "net_NOP", EventType: net_NOP, ItemType: reflect.TypeOf(dota.CNETMsg_NOP{})},
		{MapType: NET, Value: 1, Name: "net_Disconnect", EventType: net_Disconnect, ItemType: reflect.TypeOf(dota.CNETMsg_Disconnect{})},
		{MapType: NET, Value: 2, Name: "net_File", EventType: net_File, ItemType: reflect.TypeOf(dota.CNETMsg_File{})},
		{MapType: NET, Value: 3, Name: "net_SplitScreenUser", EventType: net_SplitScreenUser, ItemType: reflect.TypeOf(dota.CNETMsg_SplitScreenUser{})},
		{MapType: NET, Value: 4, Name: "net_Tick", EventType: net_Tick, ItemType: reflect.TypeOf(dota.CNETMsg_Tick{})},
		{MapType: NET, Value: 5, Name: "net_StringCmd", EventType: net_StringCmd, ItemType: reflect.TypeOf(dota.CNETMsg_StringCmd{})},
		{MapType: NET, Value: 6, Name: "net_SetConVar", EventType: net_SetConVar, ItemType: reflect.TypeOf(dota.CNETMsg_SetConVar{})},
		{MapType: NET, Value: 7, Name: "net_SignonState", EventType: net_SignonState, ItemType: reflect.TypeOf(dota.CNETMsg_SignonState{})},
		{MapType: SVC, Value: 8, Name: "svc_ServerInfo", EventType: svc_ServerInfo, ItemType: reflect.TypeOf(dota.CSVCMsg_ServerInfo{})},
		{MapType: SVC, Value: 9, Name: "svc_SendTable", EventType: svc_SendTable, ItemType: reflect.TypeOf(dota.CSVCMsg_SendTable{})},
		{MapType: SVC, Value: 10, Name: "svc_ClassInfo", EventType: svc_ClassInfo, ItemType: reflect.TypeOf(dota.CSVCMsg_ClassInfo{})},
		{MapType: SVC, Value: 11, Name: "svc_SetPause", EventType: svc_SetPause, ItemType: reflect.TypeOf(dota.CSVCMsg_SetPause{})},
		{MapType: SVC, Value: 12, Name: "svc_CreateStringTable", EventType: svc_CreateStringTable, ItemType: reflect.TypeOf(dota.CSVCMsg_CreateStringTable{})},
		{MapType: SVC, Value: 13, Name: "svc_UpdateStringTable", EventType: svc_UpdateStringTable, ItemType: reflect.TypeOf(dota.CSVCMsg_UpdateStringTable{})},
		{MapType: SVC, Value: 14, Name: "svc_VoiceInit", EventType: svc_VoiceInit, ItemType: reflect.TypeOf(dota.CSVCMsg_VoiceInit{})},
		{MapType: SVC, Value: 15, Name: "svc_VoiceData", EventType: svc_VoiceData, ItemType: reflect.TypeOf(dota.CSVCMsg_VoiceData{})},
		{MapType: SVC, Value: 16, Name: "svc_Print", EventType: svc_Print, ItemType: reflect.TypeOf(dota.CSVCMsg_Print{})},
		{MapType: SVC, Value: 17, Name: "svc_Sounds", EventType: svc_Sounds, ItemType: reflect.TypeOf(dota.CSVCMsg_Sounds{})},
		{MapType: SVC, Value: 18, Name: "svc_SetView", EventType: svc_SetView, ItemType: reflect.TypeOf(dota.CSVCMsg_SetView{})},
		{MapType: SVC, Value: 19, Name: "svc_FixAngle", EventType: svc_FixAngle, ItemType: reflect.TypeOf(dota.CSVCMsg_FixAngle{})},
		{MapType: SVC, Value: 20, Name: "svc_CrosshairAngle", EventType: svc_CrosshairAngle, ItemType: reflect.TypeOf(dota.CSVCMsg_CrosshairAngle{})},
		{MapType: SVC, Value: 21, Name: "svc_BSPDecal", EventType: svc_BSPDecal, ItemType: reflect.TypeOf(dota.CSVCMsg_BSPDecal{})},
		{MapType: SVC, Value: 22, Name: "svc_SplitScreen", EventType: svc_SplitScreen, ItemType: reflect.TypeOf(dota.CSVCMsg_SplitScreen{})},
		{MapType: SVC, Value: 23, Name: "svc_UserMessage", EventType: svc_UserMessage, ItemType: reflect.TypeOf(dota.CSVCMsg_UserMessage{})},
		{MapType: SVC, Value: 25, Name: "svc_GameEvent", EventType: svc_GameEvent, ItemType: reflect.TypeOf(dota.CSVCMsg_GameEvent{})},
		{MapType: SVC, Value: 26, Name: "svc_PacketEntities", EventType: svc_PacketEntities, ItemType: reflect.TypeOf(dota.CSVCMsg_PacketEntities{})},
		{MapType: SVC, Value: 27, Name: "svc_TempEntities", EventType: svc_TempEntities, ItemType: reflect.TypeOf(dota.CSVCMsg_TempEntities{})},
		{MapType: SVC, Value: 28, Name: "svc_Prefetch", EventType: svc_Prefetch, ItemType: reflect.TypeOf(dota.CSVCMsg_Prefetch{})},
		{MapType: SVC, Value: 29, Name: "svc_Menu", EventType: svc_Menu, ItemType: reflect.TypeOf(dota.CSVCMsg_Menu{})},
		{MapType: SVC, Value: 30, Name: "svc_GameEventList", EventType: svc_GameEventList, ItemType: reflect.TypeOf(dota.CSVCMsg_GameEventList{})},
		{MapType: SVC, Value: 31, Name: "svc_GetCvarValue", EventType: svc_GetCvarValue, ItemType: reflect.TypeOf(dota.CSVCMsg_GetCvarValue{})},
		{MapType: SVC, Value: 32, Name: "svc_PacketReliable", EventType: svc_PacketReliable, ItemType: reflect.TypeOf(dota.CSVCMsg_PacketReliable{})},
	}
	BumDum = []ParserBaseEventMap{
		{MapType: BUM, Value: 1, Name: "UM_AchievementEvent", EventType: UM_AchievementEvent, ItemType: reflect.TypeOf(dota.CUserMsg_AchievementEvent{})},
		{MapType: BUM, Value: 2, Name: "UM_CloseCaption", EventType: UM_CloseCaption, ItemType: reflect.TypeOf(dota.CUserMsg_CloseCaption{})},
		{MapType: BUM, Value: 4, Name: "UM_CurrentTimescale", EventType: UM_CurrentTimescale, ItemType: reflect.TypeOf(dota.CUserMsg_CurrentTimescale{})},
		{MapType: BUM, Value: 5, Name: "UM_DesiredTimescale", EventType: UM_DesiredTimescale, ItemType: reflect.TypeOf(dota.CUserMsg_DesiredTimescale{})},
		{MapType: BUM, Value: 6, Name: "UM_Fade", EventType: UM_Fade, ItemType: reflect.TypeOf(dota.CUserMsg_Fade{})},
		{MapType: BUM, Value: 7, Name: "UM_GameTitle", EventType: UM_GameTitle, ItemType: reflect.TypeOf(dota.CUserMsg_GameTitle{})},
		{MapType: BUM, Value: 8, Name: "UM_Geiger", EventType: UM_Geiger, ItemType: reflect.TypeOf(dota.CUserMsg_Geiger{})},
		{MapType: BUM, Value: 9, Name: "UM_HintText", EventType: UM_HintText, ItemType: reflect.TypeOf(dota.CUserMsg_HintText{})},
		{MapType: BUM, Value: 10, Name: "UM_HudMsg", EventType: UM_HudMsg, ItemType: reflect.TypeOf(dota.CUserMsg_HudMsg{})},
		{MapType: BUM, Value: 11, Name: "UM_HudText", EventType: UM_HudText, ItemType: reflect.TypeOf(dota.CUserMsg_HudText{})},
		{MapType: BUM, Value: 12, Name: "UM_KeyHintText", EventType: UM_KeyHintText, ItemType: reflect.TypeOf(dota.CUserMsg_KeyHintText{})},
		{MapType: BUM, Value: 13, Name: "UM_MessageText", EventType: UM_MessageText, ItemType: reflect.TypeOf(dota.CUserMsg_MessageText{})},
		{MapType: BUM, Value: 14, Name: "UM_RequestState", EventType: UM_RequestState, ItemType: reflect.TypeOf(dota.CUserMsg_RequestState{})},
		{MapType: BUM, Value: 15, Name: "UM_ResetHUD", EventType: UM_ResetHUD, ItemType: reflect.TypeOf(dota.CUserMsg_ResetHUD{})},
		{MapType: BUM, Value: 16, Name: "UM_Rumble", EventType: UM_Rumble, ItemType: reflect.TypeOf(dota.CUserMsg_Rumble{})},
		{MapType: BUM, Value: 17, Name: "UM_SayText", EventType: UM_SayText, ItemType: reflect.TypeOf(dota.CUserMsg_SayText{})},
		{MapType: BUM, Value: 18, Name: "UM_SayText2", EventType: UM_SayText2, ItemType: reflect.TypeOf(dota.CUserMsg_SayText2{})},
		{MapType: BUM, Value: 19, Name: "UM_SayTextChannel", EventType: UM_SayTextChannel, ItemType: reflect.TypeOf(dota.CUserMsg_SayTextChannel{})},
		{MapType: BUM, Value: 20, Name: "UM_Shake", EventType: UM_Shake, ItemType: reflect.TypeOf(dota.CUserMsg_Shake{})},
		{MapType: BUM, Value: 21, Name: "UM_ShakeDir", EventType: UM_ShakeDir, ItemType: reflect.TypeOf(dota.CUserMsg_ShakeDir{})},
		{MapType: BUM, Value: 22, Name: "UM_StatsCrawlMsg", EventType: UM_StatsCrawlMsg, ItemType: reflect.TypeOf(dota.CUserMsg_StatsCrawlMsg{})},
		{MapType: BUM, Value: 23, Name: "UM_StatsSkipState", EventType: UM_StatsSkipState, ItemType: reflect.TypeOf(dota.CUserMsg_StatsSkipState{})},
		{MapType: BUM, Value: 24, Name: "UM_TextMsg", EventType: UM_TextMsg, ItemType: reflect.TypeOf(dota.CUserMsg_TextMsg{})},
		{MapType: BUM, Value: 25, Name: "UM_Tilt", EventType: UM_Tilt, ItemType: reflect.TypeOf(dota.CUserMsg_Tilt{})},
		{MapType: BUM, Value: 26, Name: "UM_Train", EventType: UM_Train, ItemType: reflect.TypeOf(dota.CUserMsg_Train{})},
		{MapType: BUM, Value: 27, Name: "UM_VGUIMenu", EventType: UM_VGUIMenu, ItemType: reflect.TypeOf(dota.CUserMsg_VGUIMenu{})},
		{MapType: BUM, Value: 28, Name: "UM_VoiceMask", EventType: UM_VoiceMask, ItemType: reflect.TypeOf(dota.CUserMsg_VoiceMask{})},
		{MapType: BUM, Value: 29, Name: "UM_VoiceSubtitle", EventType: UM_VoiceSubtitle, ItemType: reflect.TypeOf(dota.CUserMsg_VoiceSubtitle{})},
		{MapType: BUM, Value: 30, Name: "UM_SendAudio", EventType: UM_SendAudio, ItemType: reflect.TypeOf(dota.CUserMsg_SendAudio{})},
		{MapType: DUM, Value: 65, Name: "DOTA_UM_AIDebugLine", EventType: DOTA_UM_AIDebugLine, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_AIDebugLine{})},
		{MapType: DUM, Value: 66, Name: "DOTA_UM_ChatEvent", EventType: DOTA_UM_ChatEvent, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ChatEvent{})},
		{MapType: DUM, Value: 67, Name: "DOTA_UM_CombatHeroPositions", EventType: DOTA_UM_CombatHeroPositions, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_CombatHeroPositions{})},
		{MapType: DUM, Value: 68, Name: "DOTA_UM_CombatLogData", EventType: DOTA_UM_CombatLogData, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_CombatLogData{})},
		{MapType: DUM, Value: 70, Name: "DOTA_UM_CombatLogShowDeath", EventType: DOTA_UM_CombatLogShowDeath, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_CombatLogShowDeath{})},
		{MapType: DUM, Value: 71, Name: "DOTA_UM_CreateLinearProjectile", EventType: DOTA_UM_CreateLinearProjectile, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_CreateLinearProjectile{})},
		{MapType: DUM, Value: 72, Name: "DOTA_UM_DestroyLinearProjectile", EventType: DOTA_UM_DestroyLinearProjectile, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_DestroyLinearProjectile{})},
		{MapType: DUM, Value: 73, Name: "DOTA_UM_DodgeTrackingProjectiles", EventType: DOTA_UM_DodgeTrackingProjectiles, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_DodgeTrackingProjectiles{})},
		{MapType: DUM, Value: 74, Name: "DOTA_UM_GlobalLightColor", EventType: DOTA_UM_GlobalLightColor, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_GlobalLightColor{})},
		{MapType: DUM, Value: 75, Name: "DOTA_UM_GlobalLightDirection", EventType: DOTA_UM_GlobalLightDirection, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_GlobalLightDirection{})},
		{MapType: DUM, Value: 76, Name: "DOTA_UM_InvalidCommand", EventType: DOTA_UM_InvalidCommand, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_InvalidCommand{})},
		{MapType: DUM, Value: 77, Name: "DOTA_UM_LocationPing", EventType: DOTA_UM_LocationPing, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_LocationPing{})},
		{MapType: DUM, Value: 78, Name: "DOTA_UM_MapLine", EventType: DOTA_UM_MapLine, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_MapLine{})},
		{MapType: DUM, Value: 79, Name: "DOTA_UM_MiniKillCamInfo", EventType: DOTA_UM_MiniKillCamInfo, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_MiniKillCamInfo{})},
		{MapType: DUM, Value: 80, Name: "DOTA_UM_MinimapDebugPoint", EventType: DOTA_UM_MinimapDebugPoint, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_MinimapDebugPoint{})},
		{MapType: DUM, Value: 81, Name: "DOTA_UM_MinimapEvent", EventType: DOTA_UM_MinimapEvent, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_MinimapEvent{})},
		{MapType: DUM, Value: 82, Name: "DOTA_UM_NevermoreRequiem", EventType: DOTA_UM_NevermoreRequiem, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_NevermoreRequiem{})},
		{MapType: DUM, Value: 83, Name: "DOTA_UM_OverheadEvent", EventType: DOTA_UM_OverheadEvent, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_OverheadEvent{})},
		{MapType: DUM, Value: 84, Name: "DOTA_UM_SetNextAutobuyItem", EventType: DOTA_UM_SetNextAutobuyItem, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SetNextAutobuyItem{})},
		{MapType: DUM, Value: 85, Name: "DOTA_UM_SharedCooldown", EventType: DOTA_UM_SharedCooldown, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SharedCooldown{})},
		{MapType: DUM, Value: 86, Name: "DOTA_UM_SpectatorPlayerClick", EventType: DOTA_UM_SpectatorPlayerClick, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SpectatorPlayerClick{})},
		{MapType: DUM, Value: 87, Name: "DOTA_UM_TutorialTipInfo", EventType: DOTA_UM_TutorialTipInfo, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TutorialTipInfo{})},
		{MapType: DUM, Value: 88, Name: "DOTA_UM_UnitEvent", EventType: DOTA_UM_UnitEvent, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_UnitEvent{})},
		{MapType: DUM, Value: 89, Name: "DOTA_UM_ParticleManager", EventType: DOTA_UM_ParticleManager, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ParticleManager{})},
		{MapType: DUM, Value: 90, Name: "DOTA_UM_BotChat", EventType: DOTA_UM_BotChat, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_BotChat{})},
		{MapType: DUM, Value: 91, Name: "DOTA_UM_HudError", EventType: DOTA_UM_HudError, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_HudError{})},
		{MapType: DUM, Value: 92, Name: "DOTA_UM_ItemPurchased", EventType: DOTA_UM_ItemPurchased, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ItemPurchased{})},
		{MapType: DUM, Value: 93, Name: "DOTA_UM_Ping", EventType: DOTA_UM_Ping, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_Ping{})},
		{MapType: DUM, Value: 94, Name: "DOTA_UM_ItemFound", EventType: DOTA_UM_ItemFound, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ItemFound{})},
		{MapType: DUM, Value: 96, Name: "DOTA_UM_SwapVerify", EventType: DOTA_UM_SwapVerify, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SwapVerify{})},
		{MapType: DUM, Value: 97, Name: "DOTA_UM_WorldLine", EventType: DOTA_UM_WorldLine, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_WorldLine{})},
		{MapType: DUM, Value: 98, Name: "DOTA_UM_TournamentDrop", EventType: DOTA_UM_TournamentDrop, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TournamentDrop{})},
		{MapType: DUM, Value: 99, Name: "DOTA_UM_ItemAlert", EventType: DOTA_UM_ItemAlert, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ItemAlert{})},
		{MapType: DUM, Value: 100, Name: "DOTA_UM_HalloweenDrops", EventType: DOTA_UM_HalloweenDrops, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_HalloweenDrops{})},
		{MapType: DUM, Value: 101, Name: "DOTA_UM_ChatWheel", EventType: DOTA_UM_ChatWheel, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ChatWheel{})},
		{MapType: DUM, Value: 102, Name: "DOTA_UM_ReceivedXmasGift", EventType: DOTA_UM_ReceivedXmasGift, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ReceivedXmasGift{})},
		{MapType: DUM, Value: 103, Name: "DOTA_UM_UpdateSharedContent", EventType: DOTA_UM_UpdateSharedContent, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_UpdateSharedContent{})},
		{MapType: DUM, Value: 104, Name: "DOTA_UM_TutorialRequestExp", EventType: DOTA_UM_TutorialRequestExp, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TutorialRequestExp{})},
		{MapType: DUM, Value: 105, Name: "DOTA_UM_TutorialPingMinimap", EventType: DOTA_UM_TutorialPingMinimap, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TutorialPingMinimap{})},
		{MapType: DUM, Value: 107, Name: "DOTA_UM_ShowSurvey", EventType: DOTA_UM_ShowSurvey, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ShowSurvey{})},
		{MapType: DUM, Value: 108, Name: "DOTA_UM_TutorialFade", EventType: DOTA_UM_TutorialFade, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TutorialFade{})},
		{MapType: DUM, Value: 109, Name: "DOTA_UM_AddQuestLogEntry", EventType: DOTA_UM_AddQuestLogEntry, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_AddQuestLogEntry{})},
		{MapType: DUM, Value: 110, Name: "DOTA_UM_SendStatPopup", EventType: DOTA_UM_SendStatPopup, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SendStatPopup{})},
		{MapType: DUM, Value: 111, Name: "DOTA_UM_TutorialFinish", EventType: DOTA_UM_TutorialFinish, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TutorialFinish{})},
		{MapType: DUM, Value: 112, Name: "DOTA_UM_SendRoshanPopup", EventType: DOTA_UM_SendRoshanPopup, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SendRoshanPopup{})},
		{MapType: DUM, Value: 113, Name: "DOTA_UM_SendGenericToolTip", EventType: DOTA_UM_SendGenericToolTip, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SendGenericToolTip{})},
	}
	Maps = map[string]ParserBaseEventMap{
		"DEM_Stop":                         {MapType: DEM, Value: 0, Name: "DEM_Stop", EventType: DEM_Stop, ItemType: reflect.TypeOf(dota.CDemoStop{})},
		"DEM_FileHeader":                   {MapType: DEM, Value: 1, Name: "DEM_FileHeader", EventType: DEM_FileHeader, ItemType: reflect.TypeOf(dota.CDemoFileHeader{})},
		"DEM_FileInfo":                     {MapType: DEM, Value: 2, Name: "DEM_FileInfo", EventType: DEM_FileInfo, ItemType: reflect.TypeOf(dota.CDemoFileInfo{})},
		"DEM_SyncTick":                     {MapType: DEM, Value: 3, Name: "DEM_SyncTick", EventType: DEM_SyncTick, ItemType: reflect.TypeOf(dota.CDemoSyncTick{})},
		"DEM_SendTables":                   {MapType: DEM, Value: 4, Name: "DEM_SendTables", EventType: DEM_SendTables, ItemType: reflect.TypeOf(dota.CDemoSendTables{})},
		"DEM_ClassInfo":                    {MapType: DEM, Value: 5, Name: "DEM_ClassInfo", EventType: DEM_ClassInfo, ItemType: reflect.TypeOf(dota.CDemoClassInfo{})},
		"DEM_StringTables":                 {MapType: DEM, Value: 6, Name: "DEM_StringTables", EventType: DEM_StringTables, ItemType: reflect.TypeOf(dota.CDemoStringTables{})},
		"DEM_Packet":                       {MapType: DEM, Value: 7, Name: "DEM_Packet", EventType: DEM_Packet, ItemType: reflect.TypeOf(dota.CDemoPacket{})},
		"DEM_ConsoleCmd":                   {MapType: DEM, Value: 9, Name: "DEM_ConsoleCmd", EventType: DEM_ConsoleCmd, ItemType: reflect.TypeOf(dota.CDemoConsoleCmd{})},
		"DEM_CustomData":                   {MapType: DEM, Value: 10, Name: "DEM_CustomData", EventType: DEM_CustomData, ItemType: reflect.TypeOf(dota.CDemoCustomData{})},
		"DEM_CustomDataCallbacks":          {MapType: DEM, Value: 11, Name: "DEM_CustomDataCallbacks", EventType: DEM_CustomDataCallbacks, ItemType: reflect.TypeOf(dota.CDemoCustomDataCallbacks{})},
		"DEM_UserCmd":                      {MapType: DEM, Value: 12, Name: "DEM_UserCmd", EventType: DEM_UserCmd, ItemType: reflect.TypeOf(dota.CDemoUserCmd{})},
		"DEM_FullPacket":                   {MapType: DEM, Value: 13, Name: "DEM_FullPacket", EventType: DEM_FullPacket, ItemType: reflect.TypeOf(dota.CDemoFullPacket{})},
		"net_NOP":                          {MapType: NET, Value: 0, Name: "net_NOP", EventType: net_NOP, ItemType: reflect.TypeOf(dota.CNETMsg_NOP{})},
		"net_Disconnect":                   {MapType: NET, Value: 1, Name: "net_Disconnect", EventType: net_Disconnect, ItemType: reflect.TypeOf(dota.CNETMsg_Disconnect{})},
		"net_File":                         {MapType: NET, Value: 2, Name: "net_File", EventType: net_File, ItemType: reflect.TypeOf(dota.CNETMsg_File{})},
		"net_SplitScreenUser":              {MapType: NET, Value: 3, Name: "net_SplitScreenUser", EventType: net_SplitScreenUser, ItemType: reflect.TypeOf(dota.CNETMsg_SplitScreenUser{})},
		"net_Tick":                         {MapType: NET, Value: 4, Name: "net_Tick", EventType: net_Tick, ItemType: reflect.TypeOf(dota.CNETMsg_Tick{})},
		"net_StringCmd":                    {MapType: NET, Value: 5, Name: "net_StringCmd", EventType: net_StringCmd, ItemType: reflect.TypeOf(dota.CNETMsg_StringCmd{})},
		"net_SetConVar":                    {MapType: NET, Value: 6, Name: "net_SetConVar", EventType: net_SetConVar, ItemType: reflect.TypeOf(dota.CNETMsg_SetConVar{})},
		"net_SignonState":                  {MapType: NET, Value: 7, Name: "net_SignonState", EventType: net_SignonState, ItemType: reflect.TypeOf(dota.CNETMsg_SignonState{})},
		"svc_ServerInfo":                   {MapType: SVC, Value: 8, Name: "svc_ServerInfo", EventType: svc_ServerInfo, ItemType: reflect.TypeOf(dota.CSVCMsg_ServerInfo{})},
		"svc_SendTable":                    {MapType: SVC, Value: 9, Name: "svc_SendTable", EventType: svc_SendTable, ItemType: reflect.TypeOf(dota.CSVCMsg_SendTable{})},
		"svc_ClassInfo":                    {MapType: SVC, Value: 10, Name: "svc_ClassInfo", EventType: svc_ClassInfo, ItemType: reflect.TypeOf(dota.CSVCMsg_ClassInfo{})},
		"svc_SetPause":                     {MapType: SVC, Value: 11, Name: "svc_SetPause", EventType: svc_SetPause, ItemType: reflect.TypeOf(dota.CSVCMsg_SetPause{})},
		"svc_CreateStringTable":            {MapType: SVC, Value: 12, Name: "svc_CreateStringTable", EventType: svc_CreateStringTable, ItemType: reflect.TypeOf(dota.CSVCMsg_CreateStringTable{})},
		"svc_UpdateStringTable":            {MapType: SVC, Value: 13, Name: "svc_UpdateStringTable", EventType: svc_UpdateStringTable, ItemType: reflect.TypeOf(dota.CSVCMsg_UpdateStringTable{})},
		"svc_VoiceInit":                    {MapType: SVC, Value: 14, Name: "svc_VoiceInit", EventType: svc_VoiceInit, ItemType: reflect.TypeOf(dota.CSVCMsg_VoiceInit{})},
		"svc_VoiceData":                    {MapType: SVC, Value: 15, Name: "svc_VoiceData", EventType: svc_VoiceData, ItemType: reflect.TypeOf(dota.CSVCMsg_VoiceData{})},
		"svc_Print":                        {MapType: SVC, Value: 16, Name: "svc_Print", EventType: svc_Print, ItemType: reflect.TypeOf(dota.CSVCMsg_Print{})},
		"svc_Sounds":                       {MapType: SVC, Value: 17, Name: "svc_Sounds", EventType: svc_Sounds, ItemType: reflect.TypeOf(dota.CSVCMsg_Sounds{})},
		"svc_SetView":                      {MapType: SVC, Value: 18, Name: "svc_SetView", EventType: svc_SetView, ItemType: reflect.TypeOf(dota.CSVCMsg_SetView{})},
		"svc_FixAngle":                     {MapType: SVC, Value: 19, Name: "svc_FixAngle", EventType: svc_FixAngle, ItemType: reflect.TypeOf(dota.CSVCMsg_FixAngle{})},
		"svc_CrosshairAngle":               {MapType: SVC, Value: 20, Name: "svc_CrosshairAngle", EventType: svc_CrosshairAngle, ItemType: reflect.TypeOf(dota.CSVCMsg_CrosshairAngle{})},
		"svc_BSPDecal":                     {MapType: SVC, Value: 21, Name: "svc_BSPDecal", EventType: svc_BSPDecal, ItemType: reflect.TypeOf(dota.CSVCMsg_BSPDecal{})},
		"svc_SplitScreen":                  {MapType: SVC, Value: 22, Name: "svc_SplitScreen", EventType: svc_SplitScreen, ItemType: reflect.TypeOf(dota.CSVCMsg_SplitScreen{})},
		"svc_UserMessage":                  {MapType: SVC, Value: 23, Name: "svc_UserMessage", EventType: svc_UserMessage, ItemType: reflect.TypeOf(dota.CSVCMsg_UserMessage{})},
		"svc_GameEvent":                    {MapType: SVC, Value: 25, Name: "svc_GameEvent", EventType: svc_GameEvent, ItemType: reflect.TypeOf(dota.CSVCMsg_GameEvent{})},
		"svc_PacketEntities":               {MapType: SVC, Value: 26, Name: "svc_PacketEntities", EventType: svc_PacketEntities, ItemType: reflect.TypeOf(dota.CSVCMsg_PacketEntities{})},
		"svc_TempEntities":                 {MapType: SVC, Value: 27, Name: "svc_TempEntities", EventType: svc_TempEntities, ItemType: reflect.TypeOf(dota.CSVCMsg_TempEntities{})},
		"svc_Prefetch":                     {MapType: SVC, Value: 28, Name: "svc_Prefetch", EventType: svc_Prefetch, ItemType: reflect.TypeOf(dota.CSVCMsg_Prefetch{})},
		"svc_Menu":                         {MapType: SVC, Value: 29, Name: "svc_Menu", EventType: svc_Menu, ItemType: reflect.TypeOf(dota.CSVCMsg_Menu{})},
		"svc_GameEventList":                {MapType: SVC, Value: 30, Name: "svc_GameEventList", EventType: svc_GameEventList, ItemType: reflect.TypeOf(dota.CSVCMsg_GameEventList{})},
		"svc_GetCvarValue":                 {MapType: SVC, Value: 31, Name: "svc_GetCvarValue", EventType: svc_GetCvarValue, ItemType: reflect.TypeOf(dota.CSVCMsg_GetCvarValue{})},
		"svc_PacketReliable":               {MapType: SVC, Value: 32, Name: "svc_PacketReliable", EventType: svc_PacketReliable, ItemType: reflect.TypeOf(dota.CSVCMsg_PacketReliable{})},
		"UM_AchievementEvent":              {MapType: BUM, Value: 1, Name: "UM_AchievementEvent", EventType: UM_AchievementEvent, ItemType: reflect.TypeOf(dota.CUserMsg_AchievementEvent{})},
		"UM_CloseCaption":                  {MapType: BUM, Value: 2, Name: "UM_CloseCaption", EventType: UM_CloseCaption, ItemType: reflect.TypeOf(dota.CUserMsg_CloseCaption{})},
		"UM_CurrentTimescale":              {MapType: BUM, Value: 4, Name: "UM_CurrentTimescale", EventType: UM_CurrentTimescale, ItemType: reflect.TypeOf(dota.CUserMsg_CurrentTimescale{})},
		"UM_DesiredTimescale":              {MapType: BUM, Value: 5, Name: "UM_DesiredTimescale", EventType: UM_DesiredTimescale, ItemType: reflect.TypeOf(dota.CUserMsg_DesiredTimescale{})},
		"UM_Fade":                          {MapType: BUM, Value: 6, Name: "UM_Fade", EventType: UM_Fade, ItemType: reflect.TypeOf(dota.CUserMsg_Fade{})},
		"UM_GameTitle":                     {MapType: BUM, Value: 7, Name: "UM_GameTitle", EventType: UM_GameTitle, ItemType: reflect.TypeOf(dota.CUserMsg_GameTitle{})},
		"UM_Geiger":                        {MapType: BUM, Value: 8, Name: "UM_Geiger", EventType: UM_Geiger, ItemType: reflect.TypeOf(dota.CUserMsg_Geiger{})},
		"UM_HintText":                      {MapType: BUM, Value: 9, Name: "UM_HintText", EventType: UM_HintText, ItemType: reflect.TypeOf(dota.CUserMsg_HintText{})},
		"UM_HudMsg":                        {MapType: BUM, Value: 10, Name: "UM_HudMsg", EventType: UM_HudMsg, ItemType: reflect.TypeOf(dota.CUserMsg_HudMsg{})},
		"UM_HudText":                       {MapType: BUM, Value: 11, Name: "UM_HudText", EventType: UM_HudText, ItemType: reflect.TypeOf(dota.CUserMsg_HudText{})},
		"UM_KeyHintText":                   {MapType: BUM, Value: 12, Name: "UM_KeyHintText", EventType: UM_KeyHintText, ItemType: reflect.TypeOf(dota.CUserMsg_KeyHintText{})},
		"UM_MessageText":                   {MapType: BUM, Value: 13, Name: "UM_MessageText", EventType: UM_MessageText, ItemType: reflect.TypeOf(dota.CUserMsg_MessageText{})},
		"UM_RequestState":                  {MapType: BUM, Value: 14, Name: "UM_RequestState", EventType: UM_RequestState, ItemType: reflect.TypeOf(dota.CUserMsg_RequestState{})},
		"UM_ResetHUD":                      {MapType: BUM, Value: 15, Name: "UM_ResetHUD", EventType: UM_ResetHUD, ItemType: reflect.TypeOf(dota.CUserMsg_ResetHUD{})},
		"UM_Rumble":                        {MapType: BUM, Value: 16, Name: "UM_Rumble", EventType: UM_Rumble, ItemType: reflect.TypeOf(dota.CUserMsg_Rumble{})},
		"UM_SayText":                       {MapType: BUM, Value: 17, Name: "UM_SayText", EventType: UM_SayText, ItemType: reflect.TypeOf(dota.CUserMsg_SayText{})},
		"UM_SayText2":                      {MapType: BUM, Value: 18, Name: "UM_SayText2", EventType: UM_SayText2, ItemType: reflect.TypeOf(dota.CUserMsg_SayText2{})},
		"UM_SayTextChannel":                {MapType: BUM, Value: 19, Name: "UM_SayTextChannel", EventType: UM_SayTextChannel, ItemType: reflect.TypeOf(dota.CUserMsg_SayTextChannel{})},
		"UM_Shake":                         {MapType: BUM, Value: 20, Name: "UM_Shake", EventType: UM_Shake, ItemType: reflect.TypeOf(dota.CUserMsg_Shake{})},
		"UM_ShakeDir":                      {MapType: BUM, Value: 21, Name: "UM_ShakeDir", EventType: UM_ShakeDir, ItemType: reflect.TypeOf(dota.CUserMsg_ShakeDir{})},
		"UM_StatsCrawlMsg":                 {MapType: BUM, Value: 22, Name: "UM_StatsCrawlMsg", EventType: UM_StatsCrawlMsg, ItemType: reflect.TypeOf(dota.CUserMsg_StatsCrawlMsg{})},
		"UM_StatsSkipState":                {MapType: BUM, Value: 23, Name: "UM_StatsSkipState", EventType: UM_StatsSkipState, ItemType: reflect.TypeOf(dota.CUserMsg_StatsSkipState{})},
		"UM_TextMsg":                       {MapType: BUM, Value: 24, Name: "UM_TextMsg", EventType: UM_TextMsg, ItemType: reflect.TypeOf(dota.CUserMsg_TextMsg{})},
		"UM_Tilt":                          {MapType: BUM, Value: 25, Name: "UM_Tilt", EventType: UM_Tilt, ItemType: reflect.TypeOf(dota.CUserMsg_Tilt{})},
		"UM_Train":                         {MapType: BUM, Value: 26, Name: "UM_Train", EventType: UM_Train, ItemType: reflect.TypeOf(dota.CUserMsg_Train{})},
		"UM_VGUIMenu":                      {MapType: BUM, Value: 27, Name: "UM_VGUIMenu", EventType: UM_VGUIMenu, ItemType: reflect.TypeOf(dota.CUserMsg_VGUIMenu{})},
		"UM_VoiceMask":                     {MapType: BUM, Value: 28, Name: "UM_VoiceMask", EventType: UM_VoiceMask, ItemType: reflect.TypeOf(dota.CUserMsg_VoiceMask{})},
		"UM_VoiceSubtitle":                 {MapType: BUM, Value: 29, Name: "UM_VoiceSubtitle", EventType: UM_VoiceSubtitle, ItemType: reflect.TypeOf(dota.CUserMsg_VoiceSubtitle{})},
		"UM_SendAudio":                     {MapType: BUM, Value: 30, Name: "UM_SendAudio", EventType: UM_SendAudio, ItemType: reflect.TypeOf(dota.CUserMsg_SendAudio{})},
		"DOTA_UM_AIDebugLine":              {MapType: DUM, Value: 65, Name: "DOTA_UM_AIDebugLine", EventType: DOTA_UM_AIDebugLine, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_AIDebugLine{})},
		"DOTA_UM_ChatEvent":                {MapType: DUM, Value: 66, Name: "DOTA_UM_ChatEvent", EventType: DOTA_UM_ChatEvent, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ChatEvent{})},
		"DOTA_UM_CombatHeroPositions":      {MapType: DUM, Value: 67, Name: "DOTA_UM_CombatHeroPositions", EventType: DOTA_UM_CombatHeroPositions, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_CombatHeroPositions{})},
		"DOTA_UM_CombatLogData":            {MapType: DUM, Value: 68, Name: "DOTA_UM_CombatLogData", EventType: DOTA_UM_CombatLogData, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_CombatLogData{})},
		"DOTA_UM_CombatLogShowDeath":       {MapType: DUM, Value: 70, Name: "DOTA_UM_CombatLogShowDeath", EventType: DOTA_UM_CombatLogShowDeath, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_CombatLogShowDeath{})},
		"DOTA_UM_CreateLinearProjectile":   {MapType: DUM, Value: 71, Name: "DOTA_UM_CreateLinearProjectile", EventType: DOTA_UM_CreateLinearProjectile, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_CreateLinearProjectile{})},
		"DOTA_UM_DestroyLinearProjectile":  {MapType: DUM, Value: 72, Name: "DOTA_UM_DestroyLinearProjectile", EventType: DOTA_UM_DestroyLinearProjectile, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_DestroyLinearProjectile{})},
		"DOTA_UM_DodgeTrackingProjectiles": {MapType: DUM, Value: 73, Name: "DOTA_UM_DodgeTrackingProjectiles", EventType: DOTA_UM_DodgeTrackingProjectiles, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_DodgeTrackingProjectiles{})},
		"DOTA_UM_GlobalLightColor":         {MapType: DUM, Value: 74, Name: "DOTA_UM_GlobalLightColor", EventType: DOTA_UM_GlobalLightColor, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_GlobalLightColor{})},
		"DOTA_UM_GlobalLightDirection":     {MapType: DUM, Value: 75, Name: "DOTA_UM_GlobalLightDirection", EventType: DOTA_UM_GlobalLightDirection, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_GlobalLightDirection{})},
		"DOTA_UM_InvalidCommand":           {MapType: DUM, Value: 76, Name: "DOTA_UM_InvalidCommand", EventType: DOTA_UM_InvalidCommand, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_InvalidCommand{})},
		"DOTA_UM_LocationPing":             {MapType: DUM, Value: 77, Name: "DOTA_UM_LocationPing", EventType: DOTA_UM_LocationPing, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_LocationPing{})},
		"DOTA_UM_MapLine":                  {MapType: DUM, Value: 78, Name: "DOTA_UM_MapLine", EventType: DOTA_UM_MapLine, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_MapLine{})},
		"DOTA_UM_MiniKillCamInfo":          {MapType: DUM, Value: 79, Name: "DOTA_UM_MiniKillCamInfo", EventType: DOTA_UM_MiniKillCamInfo, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_MiniKillCamInfo{})},
		"DOTA_UM_MinimapDebugPoint":        {MapType: DUM, Value: 80, Name: "DOTA_UM_MinimapDebugPoint", EventType: DOTA_UM_MinimapDebugPoint, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_MinimapDebugPoint{})},
		"DOTA_UM_MinimapEvent":             {MapType: DUM, Value: 81, Name: "DOTA_UM_MinimapEvent", EventType: DOTA_UM_MinimapEvent, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_MinimapEvent{})},
		"DOTA_UM_NevermoreRequiem":         {MapType: DUM, Value: 82, Name: "DOTA_UM_NevermoreRequiem", EventType: DOTA_UM_NevermoreRequiem, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_NevermoreRequiem{})},
		"DOTA_UM_OverheadEvent":            {MapType: DUM, Value: 83, Name: "DOTA_UM_OverheadEvent", EventType: DOTA_UM_OverheadEvent, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_OverheadEvent{})},
		"DOTA_UM_SetNextAutobuyItem":       {MapType: DUM, Value: 84, Name: "DOTA_UM_SetNextAutobuyItem", EventType: DOTA_UM_SetNextAutobuyItem, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SetNextAutobuyItem{})},
		"DOTA_UM_SharedCooldown":           {MapType: DUM, Value: 85, Name: "DOTA_UM_SharedCooldown", EventType: DOTA_UM_SharedCooldown, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SharedCooldown{})},
		"DOTA_UM_SpectatorPlayerClick":     {MapType: DUM, Value: 86, Name: "DOTA_UM_SpectatorPlayerClick", EventType: DOTA_UM_SpectatorPlayerClick, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SpectatorPlayerClick{})},
		"DOTA_UM_TutorialTipInfo":          {MapType: DUM, Value: 87, Name: "DOTA_UM_TutorialTipInfo", EventType: DOTA_UM_TutorialTipInfo, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TutorialTipInfo{})},
		"DOTA_UM_UnitEvent":                {MapType: DUM, Value: 88, Name: "DOTA_UM_UnitEvent", EventType: DOTA_UM_UnitEvent, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_UnitEvent{})},
		"DOTA_UM_ParticleManager":          {MapType: DUM, Value: 89, Name: "DOTA_UM_ParticleManager", EventType: DOTA_UM_ParticleManager, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ParticleManager{})},
		"DOTA_UM_BotChat":                  {MapType: DUM, Value: 90, Name: "DOTA_UM_BotChat", EventType: DOTA_UM_BotChat, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_BotChat{})},
		"DOTA_UM_HudError":                 {MapType: DUM, Value: 91, Name: "DOTA_UM_HudError", EventType: DOTA_UM_HudError, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_HudError{})},
		"DOTA_UM_ItemPurchased":            {MapType: DUM, Value: 92, Name: "DOTA_UM_ItemPurchased", EventType: DOTA_UM_ItemPurchased, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ItemPurchased{})},
		"DOTA_UM_Ping":                     {MapType: DUM, Value: 93, Name: "DOTA_UM_Ping", EventType: DOTA_UM_Ping, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_Ping{})},
		"DOTA_UM_ItemFound":                {MapType: DUM, Value: 94, Name: "DOTA_UM_ItemFound", EventType: DOTA_UM_ItemFound, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ItemFound{})},
		"DOTA_UM_SwapVerify":               {MapType: DUM, Value: 96, Name: "DOTA_UM_SwapVerify", EventType: DOTA_UM_SwapVerify, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SwapVerify{})},
		"DOTA_UM_WorldLine":                {MapType: DUM, Value: 97, Name: "DOTA_UM_WorldLine", EventType: DOTA_UM_WorldLine, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_WorldLine{})},
		"DOTA_UM_TournamentDrop":           {MapType: DUM, Value: 98, Name: "DOTA_UM_TournamentDrop", EventType: DOTA_UM_TournamentDrop, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TournamentDrop{})},
		"DOTA_UM_ItemAlert":                {MapType: DUM, Value: 99, Name: "DOTA_UM_ItemAlert", EventType: DOTA_UM_ItemAlert, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ItemAlert{})},
		"DOTA_UM_HalloweenDrops":           {MapType: DUM, Value: 100, Name: "DOTA_UM_HalloweenDrops", EventType: DOTA_UM_HalloweenDrops, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_HalloweenDrops{})},
		"DOTA_UM_ChatWheel":                {MapType: DUM, Value: 101, Name: "DOTA_UM_ChatWheel", EventType: DOTA_UM_ChatWheel, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ChatWheel{})},
		"DOTA_UM_ReceivedXmasGift":         {MapType: DUM, Value: 102, Name: "DOTA_UM_ReceivedXmasGift", EventType: DOTA_UM_ReceivedXmasGift, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ReceivedXmasGift{})},
		"DOTA_UM_UpdateSharedContent":      {MapType: DUM, Value: 103, Name: "DOTA_UM_UpdateSharedContent", EventType: DOTA_UM_UpdateSharedContent, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_UpdateSharedContent{})},
		"DOTA_UM_TutorialRequestExp":       {MapType: DUM, Value: 104, Name: "DOTA_UM_TutorialRequestExp", EventType: DOTA_UM_TutorialRequestExp, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TutorialRequestExp{})},
		"DOTA_UM_TutorialPingMinimap":      {MapType: DUM, Value: 105, Name: "DOTA_UM_TutorialPingMinimap", EventType: DOTA_UM_TutorialPingMinimap, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TutorialPingMinimap{})},
		"DOTA_UM_ShowSurvey":               {MapType: DUM, Value: 107, Name: "DOTA_UM_ShowSurvey", EventType: DOTA_UM_ShowSurvey, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_ShowSurvey{})},
		"DOTA_UM_TutorialFade":             {MapType: DUM, Value: 108, Name: "DOTA_UM_TutorialFade", EventType: DOTA_UM_TutorialFade, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TutorialFade{})},
		"DOTA_UM_AddQuestLogEntry":         {MapType: DUM, Value: 109, Name: "DOTA_UM_AddQuestLogEntry", EventType: DOTA_UM_AddQuestLogEntry, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_AddQuestLogEntry{})},
		"DOTA_UM_SendStatPopup":            {MapType: DUM, Value: 110, Name: "DOTA_UM_SendStatPopup", EventType: DOTA_UM_SendStatPopup, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SendStatPopup{})},
		"DOTA_UM_TutorialFinish":           {MapType: DUM, Value: 111, Name: "DOTA_UM_TutorialFinish", EventType: DOTA_UM_TutorialFinish, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_TutorialFinish{})},
		"DOTA_UM_SendRoshanPopup":          {MapType: DUM, Value: 112, Name: "DOTA_UM_SendRoshanPopup", EventType: DOTA_UM_SendRoshanPopup, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SendRoshanPopup{})},
		"DOTA_UM_SendGenericToolTip":       {MapType: DUM, Value: 113, Name: "DOTA_UM_SendGenericToolTip", EventType: DOTA_UM_SendGenericToolTip, ItemType: reflect.TypeOf(dota.CDOTAUserMsg_SendGenericToolTip{})},
	}
}
